/* eslint-disable */

const functions = require('firebase-functions')
// The Firebase Admin SDK to access Firestore.
const admin = require('firebase-admin')
admin.initializeApp()
const nodemailer = require('nodemailer')

var transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: 'soliualley@gmail.com',
    pass: 'twxtzvnisdelgwug',
  },
})
// Create and Deploy Your First Cloud Functions
// https://firebase.google.com/docs/functions/write-firebase-functions
const getYear = new Date()
const newDate = getYear.getFullYear().toString()
function reverseString(currentYear) {
  return currentYear.split('').reverse().join('')
}
const reversedYear = reverseString(newDate)
function regIdGenerator() {
  // get applicant array length

  const empty = []
  const doc = admin
    .firestore()
    .collection('users')
    .onSnapshot((doc) => {
      empty.push(doc)
    })

  // Generate Applicant Random Id
  let text = `ECHST-${reversedYear}${empty.length + 1}`
  return text
}
exports.candidateDeleted = functions.auth.user().onDelete((user) => {
  const doc = admin.firestore().collection('users').doc(user.uid)
  try {
    return doc.delete()
  } catch (error) {
    console.log(error.message)
  }
})

exports.sendWelcomeEmail = functions.auth.user().onCreate((user) => {
  const doc = admin.firestore().collection('users').doc(user.uid)
  const autoGeneratedID = regIdGenerator()
  doc.update({
    regId: autoGeneratedID,
  })

  const mailOptions = {
    from: `info@echst.com`,
    to: user.email,
    subject: `2021/2022 Undergraduate Online Application Form`,
    html: `<h3>Egbian College of Science and Technology, Minna, Niger State, Nigeria </h3>
     <p>Candidate's Application Number: ${autoGeneratedID}</p>
      <a href='https://project-egbiancohst.web.app/admission/login' target="_blank">
      Click Here to Login </a>`,
  }

  return transporter.sendMail(mailOptions, (error, data) => {
    if (error) {
      console.log(error)
      return
    }
    console.log('Sent!')
  })
})
